version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  unittest-lint-codecov:
    parallelism: 4
    resource_class: large
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.0
    

    steps:
      - checkout
      - run:
          name: Black lint check
          command: |
            sudo pip install black && cd swifter && black -l 120 --check .
      - run:
          name: Unit tests
          command: |
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
            sudo pip install -U pipenv && pipenv install && /usr/local/bin/circleci tests split swifter/swifter_tests.py --split-by=timings
      - codecov/upload:
          file: {{ coverage_report_filepath }}
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build-and-test:
    jobs:
      - unittest-lint-codecov
