version: 2
jobs:
  unittest-lint:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: manifoldai/orbyter-ml-dev:latest

    steps:
      - checkout
      - run:
          name: Black lint check
          command: |
            cd swifter && pipenv run black -l 120 --check .
      - run:
          name: Flake8 lint check
          command: |
            cd swifter && pipenv run flake8 --max-line-length 120 .
      - run:
          name: Unit tests
          command: |
            cd swifter && pipenv run nosetests

workflows:
  version: 2
  build-and-test:
    jobs:
      - unittest-lint
