version: 2
jobs:
  unittest-lint:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: manifoldai/docker-ml-dev:1.0

    steps:
      - checkout
      - run:
          name: Black lint check
          command: |
            pip install black && cd swifter && black -l 120 --check .
      - run:
          name: Flake8 lint check
          command: |
            cd swifter && flake8 --max-line-length 120 .
      - run:
          name: Unit tests
          command: |
            cd swifter && nosetests
workflows:
  version: 2
  build-and-test:
    jobs:
      - unittest-lint
